spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hr_java
    username: application
    password: test
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true